meas-service:
  s3:
    endpoint: ${S3_ENDPOINT}
    username: ${S3_USERNAME}
    password: ${S3_PASSWORD}
    bucket-name: measdata
  db:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema: measservice
    welldata-table: welldata

cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false

server:
  error:
    include-message: always

logging:
  file:
    meas-service.log

spring:
  jackson:
    serialization:
      indent_output: true