meas-service:
  s3:
    bucket-name: testbucket
  db:
    schema: measservice
    welldata-table: welldata

cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false
    credentials:
      accessKey: 123
      secretKey: 456

server:
  error:
    include-message: always

logging:
  file:
    meas-service.log

spring:
  jackson:
    serialization:
      indent_output: true