version: '3.5'

services:
  db:
    image: postgres:13-alpine
    restart: always
    hostname: measservice-db
    container_name: measservice-db
    networks:
      - private
      - phaedra2
    environment:
      - POSTGRES_DB=measservice
      - POSTGRES_USER=measservice
      - POSTGRES_PASSWORD=measservice
    volumes:
      - ./db/1-create-tables.sql:/opt/0-create-schema.sql
      - ./db/1-create-tables.sql:/opt/1-create-tables.sql
      - ./sh:/docker-entrypoint-initdb.d/
    ports:
      - 6789:5432

  objectstore:
    image: minio/minio
    hostname: measservice-objectstore
    container_name: measservice-objectstore
    networks:
      - private
    command: server /data
    environment:
      - MINIO_ROOT_USER=measservice-minio
      - MINIO_ROOT_PASSWORD=measservice-minio
    ports:
      - "9000:9000"

  app:
    image: phaedra2-measurementservice:0.0.2-SNAPSHOT
    hostname: measservice-app
    container_name: measservice-app
    networks:
      - private
      - phaedra2
    ports:
      - 3008:3008
    depends_on:
      - db
      - objectstore
    environment:
      - AWS_EC2_METADATA_DISABLED=true
      - DB_URL=jdbc:postgresql://measservice-db:5432/measservice?currentSchema=measservice
      - DB_USERNAME=measservice
      - DB_PASSWORD=measservice
      - DB_SCHEMA=measservice
      - S3_USERNAME=AKIA3HWGAIXYFRB565VB
      - S3_PASSWORD=EDBLww/4z6XzPFRkAQAm81UTBuEhyZF8h6LfLXB6
      - S3_BUCKET=phaedra2-poc-measdata
      - S3_ENDPOINT=https://s3.eu-west-1.amazonaws.com
networks:
  private:
    name: private
    external: false
  phaedra2:
    external:
      name: phaedra2
