version: '3'

services:

  db:
    image: postgres:13
    hostname: measservice-db
    container_name: measservice-db
    networks:
      - phaedra2
    environment:
      - POSTGRES_DB=measservice
      - POSTGRES_USER=measservice
      - POSTGRES_PASSWORD=measservice
    volumes:
      - ./sql/populate_database.sh:/docker-entrypoint-initdb.d/populate_database.sh:ro
      - ./sql/1-create-tables.sql:/opt/1-create-tables.sql:ro

  objectstore:
    image: minio/minio
    hostname: measservice-objectstore
    container_name: measservice-objectstore
    networks:
      - phaedra2
    command: server /data
    environment:
      - MINIO_ROOT_USER=measservice-minio
      - MINIO_ROOT_PASSWORD=measservice-minio

  app:
    image: openanalytics/phaedra2-measservice
    hostname: measservice-app
    container_name: measservice-app
    networks:
      - phaedra2
    ports:
      - 8080:8080
    depends_on:
      - db
      - objectstore
    environment:
      - AWS_EC2_METADATA_DISABLED=true
      - DB_URL=jdbc:postgresql://measservice-db:5432/measservice
      - DB_USERNAME=measservice
      - DB_PASSWORD=measservice
      - DB_SCHEMA=measservice
      - S3_USERNAME=AKIA3HWGAIXYFRB565VB
      - S3_PASSWORD=EDBLww/4z6XzPFRkAQAm81UTBuEhyZF8h6LfLXB6
      - S3_BUCKET=phaedra2-poc-measdata
      - S3_ENDPOINT=https://s3.eu-west-1.amazonaws.com

networks:
  phaedra2: