meas-service:
  s3:
    endpoint: ${S3_ENDPOINT}
    username: ${S3_USERNAME}
    password: ${S3_PASSWORD}
    bucket-name: ${S3_BUCKET}
  db:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema: ${DB_SCHEMA}

cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false

server:
  servlet:
    context-path: /phaedra/meas-service
  error:
    include-message: always
  port: 3008

logging:
  file:
    name: meas-service.log

spring:
  jackson:
    serialization:
      indent_output: true

eureka:
  client:
    enabled: true